/* This file contains paths to all images */

const Images = {
    Clara: require('../Images/Clara.jpg'),
    Nicole: require('../Images/Nicole.jpg'),
    Morgan: require('../Images/Morgan.png'),
    Jordan: require('../Images/Jordan.jpg'),
    wallet: require('../Images/wallet.png'),
    giftcards: require('../Images/giftcards.png'),
    locali: require('../Images/locali.png'),
    burger: require('../Images/burger.png'),
    stars: require('../Images/stars.png'),
    cycles: require('../Images/cycles.png'),
    locali2: require('../Images/locali2.png'),
    cycles2: require('../Images/cycles2.png'),
    greenDream: require('../Images/greenDream.png'),
    blurBackground: require('../Images/blurBackground.png'),
    locali3: require('../Images/locali3.png'),
    dashboardBackground: require('../Images/dashboardBackground.png'),
    sustainabiliTeam: require('../Images/sustainabiliTeam.png'),
    ecobros: require('../Images/ecobros.png'),
    teamSunflower: require('../Images/teamSunflower.png'),
    powerRangers: require('../Images/powerRangers.png'),
    goButton: require('../Images/goButton.png'),
    plusButton: require('../Images/plusButton.png'),
    expandedButton: require('../Images/expandedButton.png'),
    cyclingTogether: require('../Images/cyclingTogether.png'),
    shine: require('../Images/shine.png'),
    munchies: require('../Images/munchies.png'),
    haute: require('../Images/haute.png'),
    lit: require('../Images/lit.png'),
    vegOut: require('../Images/vegOut.png'),
    upcycled: require('../Images/upcycled.png'),
    farmFriends: require('../Images/farmFriends.png'),
    featuredFriendsGroup: require('../Images/featuredFriendsGroup.png'),
    food: require('../Images/food.png'),
    energy: require('../Images/energy.png'),
    fashion: require('../Images/fashion.png'),
    ecoweek: require('../Images/ecoweek.png'),
    divya: require('../Images/divya.png'),
    caleb: require('../Images/caleb.png'),
    li: require('../Images/li.png'),
    jake: require('../Images/jake.png'),
    energyMarathon: require('../Images/energyMarathon.png'),
    leaderboard: require('../Images/leaderboard.png'),
    recycle: require('../Images/recycling.jpg'),
    bike: require('../Images/biking.jpg'),
    beach: require('../Images/beach.jpg'),
    waterbottle: require('../Images/waterbottle.jpg'),
    bulk : require('../Images/bulk.jpg'),
    market : require('../Images/market.jpg'),
    bulk : require('../Images/bulk.jpg'),
    park : require('../Images/park.jpg'),
    treePlanting : require('../Images/treePlanting.jpg'),
    electricity : require('../Images/electricity.jpg'),
    fashion : require('../Images/fashion.jpg'),
    bus : require('../Images/bus.jpg'),
    compost : require('../Images/compost.jpg'),
    vegan : require('../Images/vegan.jpg'),
    groceries: require('../Images/groceries.png'),
    sort: require('../Images/sort.png'),
    led: require('../Images/led.jpg'),
    welcome1: require('../Images/welcome1.png'),
    welcome2: require('../Images/welcome2.png'),
    welcome3: require('../Images/welcome3.png'),
    welcome4: require('../Images/welcome4.png'),
    welcome5: require('../Images/welcome5.png'),
    reformation: require('../Images/reformation.png'),
    ecoroots: require('../Images/ecoroots.jpeg'),
    salad: require('../Images/salad.png'),
    background2: require('../Images/background2.png')
}

export default Images