/* This file contains paths to all images */

const Images = {
    Clara: require('../Images/Clara.jpg'),
    wallet: require('../Images/wallet.png'),
    giftcards: require('../Images/giftcards.png'),
    locali: require('../Images/locali.png'),
    burger: require('../Images/burger.png'),
    stars: require('../Images/stars.png'),
    cycles: require('../Images/cycles.png'),
    locali2: require('../Images/locali2.png'),
    cycles2: require('../Images/cycles2.png'),
    greenDream: require('../Images/greenDream.png'),
    blurBackground: require('../Images/blurBackground.png'),
    locali3: require('../Images/locali3.png'),
    dashboardBackground: require('../Images/dashboardBackground.png'),
    sustainabiliTeam: require('../Images/sustainabiliTeam.png'),
    ecobros: require('../Images/ecobros.png'),
    teamSunflower: require('../Images/teamSunflower.png'),
    powerRangers: require('../Images/powerRangers.png'),
    goButton: require('../Images/goButton.png'),
    plusButton: require('../Images/plusButton.png'),
    expandedButton: require('../Images/expandedButton.png'),
    cyclingTogether: require('../Images/cyclingTogether.png'),
    shine: require('../Images/shine.png'),
    munchies: require('../Images/munchies.png'),
    haute: require('../Images/haute.png'),
    lit: require('../Images/lit.png'),
    vegOut: require('../Images/vegOut.png'),
    upcycled: require('../Images/upcycled.png'),
    farmFriends: require('../Images/farmFriends.png'),
    featuredFriendsGroup: require('../Images/featuredFriendsGroup.png'),
    food: require('../Images/food.png'),
    energy: require('../Images/energy.png'),
    fashion: require('../Images/fashion.png'),
    ecoweek: require('../Images/ecoweek.png'),
    divya: require('../Images/divya.png'),
    caleb: require('../Images/caleb.png'),
    li: require('../Images/li.png'),
    jake: require('../Images/jake.png'),
    energyMarathon: require('../Images/energyMarathon.png'),
}

export default Images